version: "3"
services:
  postgresDB:
    container_name: project-assistant-postgresDB-dev
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file:
      - .env
    image: postgres:14.11-bullseye
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - project-assistant-dev-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - "5432:5432"

  pgadmin:
    container_name: project-assistant-pgadmin-dev
    image: dpage/pgadmin4:8.3
    ports:
      - "1339:80"
    depends_on:
      postgresDB:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json

#  nuxt:
#    image: "mdz-project-assistant-nuxt"
#    build:
#      context: .
#      dockerfile: docker/nuxt/Dockerfile.prod
#    environment:
#      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresDB:5432/${POSTGRES_DB}?schema=public #prisma migration url
#    depends_on:
#      postgresDB:
#        condition: service_healthy

volumes:
  project-assistant-dev-data:
