/**
 * MDZ Project Assistant Middleware API
 * This is the api description of the middleware for the MDZ Project Assistant.
 *
 * The version of the OpenAPI document: 1.0.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Advisor {
  id?: number;
  firstname?: string;
  lastname?: string;
  username?: string;
  email?: string;
}
