/**
 * MDZ Project Assistant Middleware API
 * This is the api description of the middleware for the MDZ Project Assistant.
 *
 * The version of the OpenAPI document: 1.0.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Customer {
  readonly id?: number;
  firstname?: string;
  lastname?: string;
  /**
   * Id of the assigned advisor.
   */
  advisor?: number;
  /**
   * List of ids of all related master data sheet documents.
   */
  masterDataSheet?: Array<number>;
}
