/**
 * MDZ Project Assistant Middleware API
 * This is the api description of the middleware for the MDZ Project Assistant.
 *
 * The version of the OpenAPI document: 1.0.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Document {
  readonly id?: number;
  readonly createdAt?: string;
  name?: string;
}
